% runmdpdemosNoPause
function runmdpdemosNoPause
 
names={'pests_simple',...
       'pests_Ix',...  
       'pests_func',... 
       'pests_g2P',...
       'pests_stages',...
       'pests_adaptive1',... 
       'pests_adaptive2',...
       'pests_pomdp',...
       'pests_sim',...
       'mergestatesdemo',...
       'epathdemo',...
       'cointoss_am',...
       'cointoss_pomdp',...
       'Anderson75',...
       'Anderson75Adaptive', ...
       };
     
for i=1:numel(names)
  rundemo(names{i})
end
       
function rundemo(name)
close all
disp(' ')
disp(['Running: ' name])
 eval(name)  
disp('done') 